name: mower_bot
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

flutter_launcher_icons:
  image_path: "launch_mower_bot_g.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "launch_mower_bot_g.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "launch_mower_bot_g.png"
  color_dark: "#000000"
  image_dark: "launch_mower_bot_g.png"
  android_12:
    image: "launch_mower_bot_g.png"
    icon_background_color: "#FFFFFF"
    image_dark: "launch_mower_bot_g.png"
    icon_background_color_dark: "#000000"
  fullscreen: true

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1
  equatable: ^2.0.7
  get_it: ^8.1.0
  web_socket_channel: ^3.0.3
  fl_chart: ^1.0.0
  json_annotation: ^4.9.0
  flutter_joystick: ^0.2.2
  http: ^1.4.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - launch_mower_bot_g.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
